CREATE DATABASE criptografia;
USE criptografia;

CREATE TABLE login (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	usuario VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    salt VARCHAR(100) NOT NULL
);

CREATE TABLE produto (
	id VARCHAR(64) PRIMARY KEY NOT NULL,
	nomeProduto VARCHAR(100) NOT NULL,
    quantidade VARCHAR(100) NOT NULL,
    dataCadastro VARCHAR(100) NOT NULL
);